---
title: "Divvy_Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dataPath1<-"/Volumes/GoogleDrive/My Drive/MScA 2022 SPRING/MSCA 31006 2 Time Series Analysis and Forecasting/Project/Data/drive-download-20220420T195243Z-001"
dataPath2<-"/Volumes/GoogleDrive/My Drive/MScA 2022 SPRING/MSCA 31006 2 Time Series Analysis and Forecasting/Project/Data/drive-download-20220420T195243Z-001/Joined_ 2017-_2021"

divvy_in <- read.csv(paste(dataPath2,'df_ts_in_1721_full.csv',sep = '/'), header=TRUE)
divvy_out <- read.csv(paste(dataPath2,'df_ts_out_1721_full.csv',sep = '/'), header=TRUE)
community <- read.csv(paste(dataPath1,'Divvy_stations_community.csv',sep = '/'), header=TRUE)

head(divvy_in)
#sum(as.numeric(divvy_in)) #ERROR

# Checking
# install.packages("gdata")
library(gdata)
colnames(divvy_in)[startsWith(colnames(divvy_in),'Indiana')==TRUE]
community$station_name[startsWith(community$station_name,'Indiana')==TRUE]

# Add new column for look-up
library(stringr)
community$station_name1 <- str_replace_all(community$station_name,' ','.')
community$station_name1 <- str_replace_all(community$station_name1,'&','.')
head(community$station_name1)

# Checking
colnames(divvy_in)[startsWith(colnames(divvy_in),'Field')==TRUE]
community$station_name[startsWith(community$station_name,'Field')==TRUE]

```

```{r}

# Prepare for clustering

# first remember the names
#timestamp_divin <- divvy_in$time_stamp
#timestamp_divout <- divvy_out$time_stamp

# transpose all but the first column (name)
#divvy_in.t <- as.data.frame(t(divvy_in[,-1]))
divvy_in.t <- as.data.frame(t(divvy_in[1:50000 ,-1]))
#colnames(divvy_in.t) <- timestamp_divin
#divvy_in.t$myfactor <- factor(row.names(divvy_in.t))
#head(divvy_in.t)
head(divvy_in.t)
sum(divvy_in.t) # 3776915

#sapply(divvy_in.t,class)

divvy_out.t <- as.data.frame(t(divvy_out[1:50000,-1]))
#colnames(divvy_out.t) <- timestamp_divout
#divvy_out.t$myfactor <- factor(row.names(divvy_out.t))
head(divvy_out.t)
sum(divvy_out.t) # 3776922

divvy_in.t10k <- as.data.frame(t(divvy_in[1:10000 ,-1]))
divvy_out.t10k <- as.data.frame(t(divvy_out[1:10000,-1]))


library(tidyverse)  # data manipulation
library(cluster)    # clustering algorithms
# install.packages("factoextra")
library(factoextra) # clustering algorithms & visualization


# Elbow Method for divvy_in.t
#fviz_nbclust(divvy_in.t1, kmeans, method = "wss")

start_time_in <- Sys.time()
fviz_nbclust(divvy_in.t, kmeans, method = "silhouette", k.max=5)
end_time_in <- Sys.time()
# 11-12 mins
# clusters = 2

start_time_out <- Sys.time()
fviz_nbclust(divvy_out.t, kmeans, method = "silhouette", k.max=5)
end_time_out <- Sys.time()
# 11-12 mins
# clusters = 2

#divvy_in.t10k <- as.data.frame(t(divvy_in[1:10000 ,-1]))
#divvy_out.t10k <- as.data.frame(t(divvy_out[1:10000,-1]))
#to try with 10k samples and k.max=10, to recheck

```
```{r}
# perform cluster in, cluster out
# append both cluster in, cluster out, + neighborhood/community
# select station with the most sum (most data point)

divvy_in.tfull <- as.data.frame(t(divvy_in[,-1]))
divvy_out.tfull <- as.data.frame(t(divvy_out[,-1]))

# https://uc-r.github.io/kmeans_clustering

k2_in <- kmeans(divvy_in.tfull, centers=2)
k2_out <- kmeans(divvy_out.tfull, centers=2)

str(k2_in) 
# bigger cluster (class 1): 745
# smaller cluster (class 2): 100
str(k2_out) 
# bigger cluster (class 1): 746
# smaller cluster (class 2): 99

library(dplyr)
# append labels and standardize cluster label as 1:small cluster, 2:big cluster
divvy_in.tfullk <- data.frame(cbind(divvy_in.tfull, clusterIn = k2_in$cluster))
head(select(divvy_in.tfullk,c('clusterIn')))
#divvy_in.tfullk$clusterIn[divvy_in.tfullk$clusterIn==2] <- 0
#divvy_in.tfullk$clusterIn[divvy_in.tfullk$clusterIn==1] <- 2
#divvy_in.tfullk$clusterIn[divvy_in.tfullk$clusterIn==0] <- 1

divvy_out.tfullk <- data.frame(cbind(divvy_out.tfull, clusterOut = k2_out$cluster))
head(select(divvy_out.tfullk,c('clusterOut')))

divvy_inout_cluster <- data.frame(cbind(divvy_in.tfullk[0], clusterIn = divvy_in.tfullk$clusterIn,
                                        clusterOut = divvy_out.tfullk$clusterOut))

divvy_inout_cluster$clusterDiff <- divvy_inout_cluster$clusterIn - divvy_inout_cluster$clusterOut
divvy_inout_cluster
length(divvy_inout_cluster$clusterDiff[divvy_inout_cluster$clusterDiff==0]) #830
length(divvy_inout_cluster$clusterDiff[divvy_inout_cluster$clusterDiff!=0]) #15

write.csv(divvy_inout_cluster,"/Volumes/GoogleDrive/My Drive/MScA 2022 SPRING/MSCA 31006 2 Time Series Analysis and Forecasting/Project/Data/drive-download-20220420T195243Z-001/divvy_inout_cluster.csv")

head(divvy_in.tfullk$clusterIn)
head(divvy_out.tfullk$clusterOut)

divvy_in.tfullk$rowsums <- rowSums(divvy_in.tfullk)-divvy_in.tfullk$clusterIn
divvy_out.tfullk$rowsums <- rowSums(divvy_out.tfullk)-divvy_out.tfullk$clusterOut

#divvy_in.tfullk = subset(divvy_in.tfullk, select = -c(rowSums) )
#divvy_out.tfullk = subset(divvy_out.tfullk, select = -c(rowSums) )

divvy_in.tfullk[order(-divvy_in.tfullk$rowsums),][divvy_in.tfullk$clusterIn==1,][1:5,]
# NA., Streeter.Dr...Grand.Ave, Lake.Shore.Dr...North.Blvd, Clinton.St...Madison.St, Theater.on.the.Lake

divvy_out.tfullk[order(-divvy_out.tfullk$rowsums),][divvy_out.tfullk$clusterOut==1,][1:5,]
# NA., Streeter.Dr...Grand.Ave, Canal.St...Adams.St, Clinton.St...Madison.St, Clinton.St...Washington.Blvd

divvy_in.tfullk[order(-divvy_in.tfullk$rowsums),][divvy_in.tfullk$clusterIn==2,][1:10,]
# Canal.St...Adams.St, Clifton.Ave...Armitage.Ave, Calumet.Ave...18th.St, May.St...Taylor.St, MLK.Jr.Dr...29th.St, State.St...Harrison.St, Larrabee.St...Armitage.Ave, Paulina.Ave...North.Ave, Noble.St...Milwaukee.Ave, Broadway...Berwyn.Ave

divvy_out.tfullk[order(-divvy_out.tfullk$rowsums),][divvy_out.tfullk$clusterOut==2,][1:10,]
# Lake.Shore.Dr...Monroe.St, Jefferson.St...Monroe.St, Damen.Ave...Division.St, Broadway...Sheridan.Rd, Canal.St...Jackson.Blvd, Larrabee.St...Armitage.Ave, Halsted.St...Clybourn.Ave, Lincoln.Ave...Belmont.Ave, Ellis.Ave...60th.St, Ellis.Ave...55th.St

# Cluster 1: Streeter.Dr...Grand.Ave
# Cluster 2: Larrabee.St...Armitage.Ave

```

```{r}

c1_in <- select(divvy_in, c('time_stamp', 'Streeter.Dr...Grand.Ave'))
c1_out <- select(divvy_out, c('time_stamp', 'Streeter.Dr...Grand.Ave'))
c2_in <- select(divvy_in, c('time_stamp', 'Larrabee.St...Armitage.Ave'))
c2_out <- select(divvy_out, c('time_stamp', 'Larrabee.St...Armitage.Ave'))

c1_in$time_stamp <- strptime(c1_in$time_stamp, '%Y-%m-%d %H:%M:%S', tz="America/Chicago")
c1_out$time_stamp <- strptime(c1_out$time_stamp, '%Y-%m-%d %H:%M:%S', tz="America/Chicago")
c2_in$time_stamp <- strptime(c2_in$time_stamp, '%Y-%m-%d %H:%M:%S', tz="America/Chicago")
c2_out$time_stamp <- strptime(c2_out$time_stamp, '%Y-%m-%d %H:%M:%S', tz="America/Chicago")

dim(c1_in) # 245478      2
dim(c1_out)
dim(c2_in)
dim(c2_out)


```

```{r}

# Cluster 1: Streeter.Dr...Grand.Ave
# Cluster 2: Larrabee.St...Armitage.Ave

plot(c1_in,type='l',main='Streeter Dr & Grand Ave (IN)')
plot(c1_out,type='l',main='Streeter Dr & Grand Ave (OUT)')
plot(c1_in, type='l',main='Larrabee.St & Armitage Ave (IN)')
plot(c1_out, type='l',main='Larrabee.St & Armitage Ave (OUT)')


```
```{r}

c1_in_ADI <- length(c1_in$Streeter.Dr...Grand.Ave)/
  length(c1_in$Streeter.Dr...Grand.Ave[c1_in$Streeter.Dr...Grand.Ave!=0])
c1_out_ADI <- length(c1_out$Streeter.Dr...Grand.Ave)/
  length(c1_out$Streeter.Dr...Grand.Ave[c1_out$Streeter.Dr...Grand.Ave!=0])
c2_in_ADI <- length(c2_in$Larrabee.St...Armitage.Ave)/
  length(c2_in$Larrabee.St...Armitage.Ave[c2_in$Larrabee.St...Armitage.Ave!=0])
c2_out_ADI <- length(c2_out$Larrabee.St...Armitage.Ave)/
  length(c2_out$Larrabee.St...Armitage.Ave[c2_out$Larrabee.St...Armitage.Ave!=0])

c1_in_ADI # 3.333261
c1_out_ADI # 3.367002
c2_in_ADI # 9.389818
c2_out_ADI # 8.995822

c1_in_CV2 <- (sd(c1_in$Streeter.Dr...Grand.Ave)/mean(c1_in$Streeter.Dr...Grand.Ave))^2
c1_out_CV2 <- (sd(c1_out$Streeter.Dr...Grand.Ave)/mean(c1_out$Streeter.Dr...Grand.Ave))^2
c2_in_CV2 <- (sd(c2_in$Larrabee.St...Armitage.Ave)/mean(c2_in$Larrabee.St...Armitage.Ave))^2
c2_out_CV2 <- (sd(c2_out$Larrabee.St...Armitage.Ave)/mean(c2_out$Larrabee.St...Armitage.Ave))^2

c1_in_CV2 # 5.822881
c1_out_CV2 # 5.651016
c2_in_CV2 # 11.21616
c2_out_CV2 # 10.51602

library(lubridate)
hour(as.POSIXct(c1_in$time_stamp))


#c1_in %>% 
#  mutate(hour_of_day = hour(as.POSIXct(c1_in$time_stamp))) %>% 
#  group_by(hour_of_day) %>% 
#  summarise(sumStreeter.Dr...Grand.Ave = sum(Streeter.Dr...Grand.Ave))

# vars(Streeter.Dr...Grand.Ave), list(Streeter.Dr...Grand.Ave=sum)

c1_in_hr <- aggregate(c1_in$Streeter.Dr...Grand.Ave, 
                 list(hour=cut(as.POSIXct(c1_in$time_stamp), "hour")), sum)
c1_out_hr <- aggregate(c1_out$Streeter.Dr...Grand.Ave, 
                 list(hour=cut(as.POSIXct(c1_out$time_stamp), "hour")), sum)
c2_in_hr <- aggregate(c2_in$Larrabee.St...Armitage.Ave, 
                 list(hour=cut(as.POSIXct(c2_in$time_stamp), "hour")), sum)
c2_out_hr <- aggregate(c2_out$Larrabee.St...Armitage.Ave, 
                 list(hour=cut(as.POSIXct(c2_out$time_stamp), "hour")), sum)

head(c1_in_hr)

c1_in_hr_ADI <- length(c1_in_hr$x)/
  length(c1_in_hr$x[c1_in_hr$x!=0])
c1_out_hr_ADI <- length(c1_out_hr$x)/
  length(c1_out_hr$x[c1_out_hr$x!=0])
c2_in_hr_ADI <- length(c2_in_hr$x)/
  length(c2_in_hr$x[c2_in_hr$x!=0])
c2_out_hr_ADI <- length(c2_out_hr$x)/
  length(c2_out_hr$x[c2_out_hr$x!=0])

c1_in_hr_ADI # 1.872351
c1_out_hr_ADI # 1.851421
c2_in_hr_ADI #  2.740788
c2_out_hr_ADI # 2.577919

c1_in_hr_CV2 <- (sd(c1_in_hr$x)/mean(c1_in_hr$x))^2
c1_out_hr_CV2 <- (sd(c1_out_hr$x)/mean(c1_out_hr$x))^2
c2_in_hr_CV2 <- (sd(c2_in_hr$x)/mean(c2_in_hr$x))^2
c2_out_hr_CV2 <- (sd(c2_out_hr$x)/mean(c2_out_hr$x))^2

# Range 3.2-4.5

```

```{r}

# first remember the names
timestamp_divin <- divvy_in$time_stamp
timestamp_divout <- divvy_out$time_stamp

# transpose all but the first column (name)
divvy_in.tfull <- as.data.frame(t(divvy_in[,-1]))
colnames(divvy_in.tfull) <- timestamp_divin
divvy_in.tfull$myfactor <- factor(row.names(divvy_in.tfull))
head(divvy_in.tfull)


divvy_out.tfull <- as.data.frame(t(divvy_out[,-1]))
colnames(divvy_out.tfull) <- timestamp_divout
divvy_out.tfull$myfactor <- factor(row.names(divvy_out.tfull))
head(divvy_out.tfull)

divvy_inout_cluster <- read.csv(paste(dataPath1,'divvy_inout_cluster.csv',sep = '/'), header=TRUE)

# Checking: they are still in the same order
head(divvy_in.tfull[0])
head(divvy_out.tfull[0])
head(divvy_inout_cluster$X)

divvy_in.tfullk2 <- data.frame(cbind(divvy_in.tfull, clusterIn = divvy_inout_cluster$clusterIn))
divvy_out.tfullk2 <- data.frame(cbind(divvy_out.tfull, clusterOut = divvy_inout_cluster$clusterOut))

head(divvy_in.tfullk2$clusterIn)
head(divvy_out.tfullk2$clusterOut)

divvy_in.tfullk2 %>% 
  group_by(clusterIn) %>% 
  summarise_at(vars(colnames(divvy_in.tfullk2)[1:245478]), sum(colnames(divvy_in.tfullk2)[1:245478]))

divvy_in.tfullk2 %>% 
  group_by(clusterIn)

colnames(divvy_in.tfullk2)[245479] #myfactor
colnames(divvy_in.tfullk2)[245480] #clusterIn

head(divvy_in.tfullk2$myfactor) # same as row names
head(divvy_out.tfullk2[0]) # row names

typeof(colnames(divvy_in.tfullk2)[1:3])
as.list(str_replace_all(strsplit(colnames(divvy_in.tfullk2)[1:3],' '),'"',''))

divvy_in.tfullk2[1]
divvy_in.tfullk2_agg <- aggregate(.~clusterIn, data=divvy_in.tfullk2, FUN=sum)

```


